spring.application.name=hr-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/hr_platform
spring.datasource.username=hr_platform
spring.datasource.password=hr_platform
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true