spring.application.name=hr-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/hr_platform
spring.datasource.username=hr_platform
spring.datasource.password=hr_platform
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
app.jwt.secret=change-this-secret-key-must-be-at-least-256-bits-long-for-hs256
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000